package com.nami.hamakko.mybatis.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;

import com.nami.hamakko.mybatis.domain.MUserInfo;
import com.nami.hamakko.mybatis.domain.MUserInfoExample;

public interface MUserInfoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hamakko.m_user_info
	 * @mbg.generated  Tue Jun 16 12:46:54 JST 2020
	 */
	long countByExample(MUserInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hamakko.m_user_info
	 * @mbg.generated  Tue Jun 16 12:46:54 JST 2020
	 */
	int deleteByExample(MUserInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hamakko.m_user_info
	 * @mbg.generated  Tue Jun 16 12:46:54 JST 2020
	 */
	int deleteByPrimaryKey(String user_id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hamakko.m_user_info
	 * @mbg.generated  Tue Jun 16 12:46:54 JST 2020
	 */
	int insert(MUserInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hamakko.m_user_info
	 * @mbg.generated  Tue Jun 16 12:46:54 JST 2020
	 */
	int insertSelective(MUserInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hamakko.m_user_info
	 * @mbg.generated  Tue Jun 16 12:46:54 JST 2020
	 */
	List<MUserInfo> selectByExample(MUserInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hamakko.m_user_info
	 * @mbg.generated  Tue Jun 16 12:46:54 JST 2020
	 */
	MUserInfo selectByPrimaryKey(String user_id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hamakko.m_user_info
	 * @mbg.generated  Tue Jun 16 12:46:54 JST 2020
	 */
	int updateByExampleSelective(@Param("record") MUserInfo record, @Param("example") MUserInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hamakko.m_user_info
	 * @mbg.generated  Tue Jun 16 12:46:54 JST 2020
	 */
	int updateByExample(@Param("record") MUserInfo record, @Param("example") MUserInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hamakko.m_user_info
	 * @mbg.generated  Tue Jun 16 12:46:54 JST 2020
	 */
	int updateByPrimaryKeySelective(MUserInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hamakko.m_user_info
	 * @mbg.generated  Tue Jun 16 12:46:54 JST 2020
	 */
	int updateByPrimaryKey(MUserInfo record);
}