package com.nami.hamakko.mybatis.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;

import com.nami.hamakko.mybatis.domain.TChusenInfo;
import com.nami.hamakko.mybatis.domain.TChusenInfoExample;
import com.nami.hamakko.mybatis.domain.TChusenInfoKey;

public interface TChusenInfoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hamakko.t_chusen_info
	 * @mbg.generated  Tue Jun 16 11:46:38 JST 2020
	 */
	long countByExample(TChusenInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hamakko.t_chusen_info
	 * @mbg.generated  Tue Jun 16 11:46:38 JST 2020
	 */
	int deleteByExample(TChusenInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hamakko.t_chusen_info
	 * @mbg.generated  Tue Jun 16 11:46:38 JST 2020
	 */
	int deleteByPrimaryKey(TChusenInfoKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hamakko.t_chusen_info
	 * @mbg.generated  Tue Jun 16 11:46:38 JST 2020
	 */
	int insert(TChusenInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hamakko.t_chusen_info
	 * @mbg.generated  Tue Jun 16 11:46:38 JST 2020
	 */
	int insertSelective(TChusenInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hamakko.t_chusen_info
	 * @mbg.generated  Tue Jun 16 11:46:38 JST 2020
	 */
	List<TChusenInfo> selectByExample(TChusenInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hamakko.t_chusen_info
	 * @mbg.generated  Tue Jun 16 11:46:38 JST 2020
	 */
	TChusenInfo selectByPrimaryKey(TChusenInfoKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hamakko.t_chusen_info
	 * @mbg.generated  Tue Jun 16 11:46:38 JST 2020
	 */
	int updateByExampleSelective(@Param("record") TChusenInfo record, @Param("example") TChusenInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hamakko.t_chusen_info
	 * @mbg.generated  Tue Jun 16 11:46:38 JST 2020
	 */
	int updateByExample(@Param("record") TChusenInfo record, @Param("example") TChusenInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hamakko.t_chusen_info
	 * @mbg.generated  Tue Jun 16 11:46:38 JST 2020
	 */
	int updateByPrimaryKeySelective(TChusenInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hamakko.t_chusen_info
	 * @mbg.generated  Tue Jun 16 11:46:38 JST 2020
	 */
	int updateByPrimaryKey(TChusenInfo record);
}