package com.nami.hamakko.mybatis.domain;

import java.util.Date;

public class MUserInfo {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hamakko.m_user_info.user_id
	 * @mbg.generated  Tue Jun 16 12:46:54 JST 2020
	 */
	private String user_id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hamakko.m_user_info.password
	 * @mbg.generated  Tue Jun 16 12:46:54 JST 2020
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hamakko.m_user_info.regist_user_id
	 * @mbg.generated  Tue Jun 16 12:46:54 JST 2020
	 */
	private String regist_user_id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hamakko.m_user_info.update_user_id
	 * @mbg.generated  Tue Jun 16 12:46:54 JST 2020
	 */
	private String update_user_id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hamakko.m_user_info.regist_timestamp
	 * @mbg.generated  Tue Jun 16 12:46:54 JST 2020
	 */
	private Date regist_timestamp;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hamakko.m_user_info.update_timestamp
	 * @mbg.generated  Tue Jun 16 12:46:54 JST 2020
	 */
	private Date update_timestamp;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hamakko.m_user_info.user_id
	 * @return  the value of hamakko.m_user_info.user_id
	 * @mbg.generated  Tue Jun 16 12:46:54 JST 2020
	 */
	public String getUser_id() {
		return user_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hamakko.m_user_info.user_id
	 * @param user_id  the value for hamakko.m_user_info.user_id
	 * @mbg.generated  Tue Jun 16 12:46:54 JST 2020
	 */
	public void setUser_id(String user_id) {
		this.user_id = user_id == null ? null : user_id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hamakko.m_user_info.password
	 * @return  the value of hamakko.m_user_info.password
	 * @mbg.generated  Tue Jun 16 12:46:54 JST 2020
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hamakko.m_user_info.password
	 * @param password  the value for hamakko.m_user_info.password
	 * @mbg.generated  Tue Jun 16 12:46:54 JST 2020
	 */
	public void setPassword(String password) {
		this.password = password == null ? null : password.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hamakko.m_user_info.regist_user_id
	 * @return  the value of hamakko.m_user_info.regist_user_id
	 * @mbg.generated  Tue Jun 16 12:46:54 JST 2020
	 */
	public String getRegist_user_id() {
		return regist_user_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hamakko.m_user_info.regist_user_id
	 * @param regist_user_id  the value for hamakko.m_user_info.regist_user_id
	 * @mbg.generated  Tue Jun 16 12:46:54 JST 2020
	 */
	public void setRegist_user_id(String regist_user_id) {
		this.regist_user_id = regist_user_id == null ? null : regist_user_id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hamakko.m_user_info.update_user_id
	 * @return  the value of hamakko.m_user_info.update_user_id
	 * @mbg.generated  Tue Jun 16 12:46:54 JST 2020
	 */
	public String getUpdate_user_id() {
		return update_user_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hamakko.m_user_info.update_user_id
	 * @param update_user_id  the value for hamakko.m_user_info.update_user_id
	 * @mbg.generated  Tue Jun 16 12:46:54 JST 2020
	 */
	public void setUpdate_user_id(String update_user_id) {
		this.update_user_id = update_user_id == null ? null : update_user_id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hamakko.m_user_info.regist_timestamp
	 * @return  the value of hamakko.m_user_info.regist_timestamp
	 * @mbg.generated  Tue Jun 16 12:46:54 JST 2020
	 */
	public Date getRegist_timestamp() {
		return regist_timestamp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hamakko.m_user_info.regist_timestamp
	 * @param regist_timestamp  the value for hamakko.m_user_info.regist_timestamp
	 * @mbg.generated  Tue Jun 16 12:46:54 JST 2020
	 */
	public void setRegist_timestamp(Date regist_timestamp) {
		this.regist_timestamp = regist_timestamp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hamakko.m_user_info.update_timestamp
	 * @return  the value of hamakko.m_user_info.update_timestamp
	 * @mbg.generated  Tue Jun 16 12:46:54 JST 2020
	 */
	public Date getUpdate_timestamp() {
		return update_timestamp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hamakko.m_user_info.update_timestamp
	 * @param update_timestamp  the value for hamakko.m_user_info.update_timestamp
	 * @mbg.generated  Tue Jun 16 12:46:54 JST 2020
	 */
	public void setUpdate_timestamp(Date update_timestamp) {
		this.update_timestamp = update_timestamp;
	}
}