package com.nami.hamakko.mybatis.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class TChusenInfoExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table hamakko.t_chusen_info
	 * @mbg.generated  Tue Jun 16 11:46:38 JST 2020
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table hamakko.t_chusen_info
	 * @mbg.generated  Tue Jun 16 11:46:38 JST 2020
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table hamakko.t_chusen_info
	 * @mbg.generated  Tue Jun 16 11:46:38 JST 2020
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hamakko.t_chusen_info
	 * @mbg.generated  Tue Jun 16 11:46:38 JST 2020
	 */
	public TChusenInfoExample() {
		oredCriteria = new ArrayList<>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hamakko.t_chusen_info
	 * @mbg.generated  Tue Jun 16 11:46:38 JST 2020
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hamakko.t_chusen_info
	 * @mbg.generated  Tue Jun 16 11:46:38 JST 2020
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hamakko.t_chusen_info
	 * @mbg.generated  Tue Jun 16 11:46:38 JST 2020
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hamakko.t_chusen_info
	 * @mbg.generated  Tue Jun 16 11:46:38 JST 2020
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hamakko.t_chusen_info
	 * @mbg.generated  Tue Jun 16 11:46:38 JST 2020
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hamakko.t_chusen_info
	 * @mbg.generated  Tue Jun 16 11:46:38 JST 2020
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hamakko.t_chusen_info
	 * @mbg.generated  Tue Jun 16 11:46:38 JST 2020
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hamakko.t_chusen_info
	 * @mbg.generated  Tue Jun 16 11:46:38 JST 2020
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hamakko.t_chusen_info
	 * @mbg.generated  Tue Jun 16 11:46:38 JST 2020
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hamakko.t_chusen_info
	 * @mbg.generated  Tue Jun 16 11:46:38 JST 2020
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table hamakko.t_chusen_info
	 * @mbg.generated  Tue Jun 16 11:46:38 JST 2020
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		protected void addCriterionForJDBCDate(String condition, Date value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value.getTime()), property);
		}

		protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property + " cannot be null or empty");
			}
			List<java.sql.Date> dateList = new ArrayList<>();
			Iterator<Date> iter = values.iterator();
			while (iter.hasNext()) {
				dateList.add(new java.sql.Date(iter.next().getTime()));
			}
			addCriterion(condition, dateList, property);
		}

		protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
		}

		public Criteria andSisetsu_codeIsNull() {
			addCriterion("sisetsu_code is null");
			return (Criteria) this;
		}

		public Criteria andSisetsu_codeIsNotNull() {
			addCriterion("sisetsu_code is not null");
			return (Criteria) this;
		}

		public Criteria andSisetsu_codeEqualTo(String value) {
			addCriterion("sisetsu_code =", value, "sisetsu_code");
			return (Criteria) this;
		}

		public Criteria andSisetsu_codeNotEqualTo(String value) {
			addCriterion("sisetsu_code <>", value, "sisetsu_code");
			return (Criteria) this;
		}

		public Criteria andSisetsu_codeGreaterThan(String value) {
			addCriterion("sisetsu_code >", value, "sisetsu_code");
			return (Criteria) this;
		}

		public Criteria andSisetsu_codeGreaterThanOrEqualTo(String value) {
			addCriterion("sisetsu_code >=", value, "sisetsu_code");
			return (Criteria) this;
		}

		public Criteria andSisetsu_codeLessThan(String value) {
			addCriterion("sisetsu_code <", value, "sisetsu_code");
			return (Criteria) this;
		}

		public Criteria andSisetsu_codeLessThanOrEqualTo(String value) {
			addCriterion("sisetsu_code <=", value, "sisetsu_code");
			return (Criteria) this;
		}

		public Criteria andSisetsu_codeLike(String value) {
			addCriterion("sisetsu_code like", value, "sisetsu_code");
			return (Criteria) this;
		}

		public Criteria andSisetsu_codeNotLike(String value) {
			addCriterion("sisetsu_code not like", value, "sisetsu_code");
			return (Criteria) this;
		}

		public Criteria andSisetsu_codeIn(List<String> values) {
			addCriterion("sisetsu_code in", values, "sisetsu_code");
			return (Criteria) this;
		}

		public Criteria andSisetsu_codeNotIn(List<String> values) {
			addCriterion("sisetsu_code not in", values, "sisetsu_code");
			return (Criteria) this;
		}

		public Criteria andSisetsu_codeBetween(String value1, String value2) {
			addCriterion("sisetsu_code between", value1, value2, "sisetsu_code");
			return (Criteria) this;
		}

		public Criteria andSisetsu_codeNotBetween(String value1, String value2) {
			addCriterion("sisetsu_code not between", value1, value2, "sisetsu_code");
			return (Criteria) this;
		}

		public Criteria andYoyaku_jikanIsNull() {
			addCriterion("yoyaku_jikan is null");
			return (Criteria) this;
		}

		public Criteria andYoyaku_jikanIsNotNull() {
			addCriterion("yoyaku_jikan is not null");
			return (Criteria) this;
		}

		public Criteria andYoyaku_jikanEqualTo(Date value) {
			addCriterionForJDBCDate("yoyaku_jikan =", value, "yoyaku_jikan");
			return (Criteria) this;
		}

		public Criteria andYoyaku_jikanNotEqualTo(Date value) {
			addCriterionForJDBCDate("yoyaku_jikan <>", value, "yoyaku_jikan");
			return (Criteria) this;
		}

		public Criteria andYoyaku_jikanGreaterThan(Date value) {
			addCriterionForJDBCDate("yoyaku_jikan >", value, "yoyaku_jikan");
			return (Criteria) this;
		}

		public Criteria andYoyaku_jikanGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("yoyaku_jikan >=", value, "yoyaku_jikan");
			return (Criteria) this;
		}

		public Criteria andYoyaku_jikanLessThan(Date value) {
			addCriterionForJDBCDate("yoyaku_jikan <", value, "yoyaku_jikan");
			return (Criteria) this;
		}

		public Criteria andYoyaku_jikanLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("yoyaku_jikan <=", value, "yoyaku_jikan");
			return (Criteria) this;
		}

		public Criteria andYoyaku_jikanIn(List<Date> values) {
			addCriterionForJDBCDate("yoyaku_jikan in", values, "yoyaku_jikan");
			return (Criteria) this;
		}

		public Criteria andYoyaku_jikanNotIn(List<Date> values) {
			addCriterionForJDBCDate("yoyaku_jikan not in", values, "yoyaku_jikan");
			return (Criteria) this;
		}

		public Criteria andYoyaku_jikanBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("yoyaku_jikan between", value1, value2, "yoyaku_jikan");
			return (Criteria) this;
		}

		public Criteria andYoyaku_jikanNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("yoyaku_jikan not between", value1, value2, "yoyaku_jikan");
			return (Criteria) this;
		}

		public Criteria andRegist_user_idIsNull() {
			addCriterion("regist_user_id is null");
			return (Criteria) this;
		}

		public Criteria andRegist_user_idIsNotNull() {
			addCriterion("regist_user_id is not null");
			return (Criteria) this;
		}

		public Criteria andRegist_user_idEqualTo(String value) {
			addCriterion("regist_user_id =", value, "regist_user_id");
			return (Criteria) this;
		}

		public Criteria andRegist_user_idNotEqualTo(String value) {
			addCriterion("regist_user_id <>", value, "regist_user_id");
			return (Criteria) this;
		}

		public Criteria andRegist_user_idGreaterThan(String value) {
			addCriterion("regist_user_id >", value, "regist_user_id");
			return (Criteria) this;
		}

		public Criteria andRegist_user_idGreaterThanOrEqualTo(String value) {
			addCriterion("regist_user_id >=", value, "regist_user_id");
			return (Criteria) this;
		}

		public Criteria andRegist_user_idLessThan(String value) {
			addCriterion("regist_user_id <", value, "regist_user_id");
			return (Criteria) this;
		}

		public Criteria andRegist_user_idLessThanOrEqualTo(String value) {
			addCriterion("regist_user_id <=", value, "regist_user_id");
			return (Criteria) this;
		}

		public Criteria andRegist_user_idLike(String value) {
			addCriterion("regist_user_id like", value, "regist_user_id");
			return (Criteria) this;
		}

		public Criteria andRegist_user_idNotLike(String value) {
			addCriterion("regist_user_id not like", value, "regist_user_id");
			return (Criteria) this;
		}

		public Criteria andRegist_user_idIn(List<String> values) {
			addCriterion("regist_user_id in", values, "regist_user_id");
			return (Criteria) this;
		}

		public Criteria andRegist_user_idNotIn(List<String> values) {
			addCriterion("regist_user_id not in", values, "regist_user_id");
			return (Criteria) this;
		}

		public Criteria andRegist_user_idBetween(String value1, String value2) {
			addCriterion("regist_user_id between", value1, value2, "regist_user_id");
			return (Criteria) this;
		}

		public Criteria andRegist_user_idNotBetween(String value1, String value2) {
			addCriterion("regist_user_id not between", value1, value2, "regist_user_id");
			return (Criteria) this;
		}

		public Criteria andUpdate_user_idIsNull() {
			addCriterion("update_user_id is null");
			return (Criteria) this;
		}

		public Criteria andUpdate_user_idIsNotNull() {
			addCriterion("update_user_id is not null");
			return (Criteria) this;
		}

		public Criteria andUpdate_user_idEqualTo(String value) {
			addCriterion("update_user_id =", value, "update_user_id");
			return (Criteria) this;
		}

		public Criteria andUpdate_user_idNotEqualTo(String value) {
			addCriterion("update_user_id <>", value, "update_user_id");
			return (Criteria) this;
		}

		public Criteria andUpdate_user_idGreaterThan(String value) {
			addCriterion("update_user_id >", value, "update_user_id");
			return (Criteria) this;
		}

		public Criteria andUpdate_user_idGreaterThanOrEqualTo(String value) {
			addCriterion("update_user_id >=", value, "update_user_id");
			return (Criteria) this;
		}

		public Criteria andUpdate_user_idLessThan(String value) {
			addCriterion("update_user_id <", value, "update_user_id");
			return (Criteria) this;
		}

		public Criteria andUpdate_user_idLessThanOrEqualTo(String value) {
			addCriterion("update_user_id <=", value, "update_user_id");
			return (Criteria) this;
		}

		public Criteria andUpdate_user_idLike(String value) {
			addCriterion("update_user_id like", value, "update_user_id");
			return (Criteria) this;
		}

		public Criteria andUpdate_user_idNotLike(String value) {
			addCriterion("update_user_id not like", value, "update_user_id");
			return (Criteria) this;
		}

		public Criteria andUpdate_user_idIn(List<String> values) {
			addCriterion("update_user_id in", values, "update_user_id");
			return (Criteria) this;
		}

		public Criteria andUpdate_user_idNotIn(List<String> values) {
			addCriterion("update_user_id not in", values, "update_user_id");
			return (Criteria) this;
		}

		public Criteria andUpdate_user_idBetween(String value1, String value2) {
			addCriterion("update_user_id between", value1, value2, "update_user_id");
			return (Criteria) this;
		}

		public Criteria andUpdate_user_idNotBetween(String value1, String value2) {
			addCriterion("update_user_id not between", value1, value2, "update_user_id");
			return (Criteria) this;
		}

		public Criteria andRegist_timestampIsNull() {
			addCriterion("regist_timestamp is null");
			return (Criteria) this;
		}

		public Criteria andRegist_timestampIsNotNull() {
			addCriterion("regist_timestamp is not null");
			return (Criteria) this;
		}

		public Criteria andRegist_timestampEqualTo(Date value) {
			addCriterion("regist_timestamp =", value, "regist_timestamp");
			return (Criteria) this;
		}

		public Criteria andRegist_timestampNotEqualTo(Date value) {
			addCriterion("regist_timestamp <>", value, "regist_timestamp");
			return (Criteria) this;
		}

		public Criteria andRegist_timestampGreaterThan(Date value) {
			addCriterion("regist_timestamp >", value, "regist_timestamp");
			return (Criteria) this;
		}

		public Criteria andRegist_timestampGreaterThanOrEqualTo(Date value) {
			addCriterion("regist_timestamp >=", value, "regist_timestamp");
			return (Criteria) this;
		}

		public Criteria andRegist_timestampLessThan(Date value) {
			addCriterion("regist_timestamp <", value, "regist_timestamp");
			return (Criteria) this;
		}

		public Criteria andRegist_timestampLessThanOrEqualTo(Date value) {
			addCriterion("regist_timestamp <=", value, "regist_timestamp");
			return (Criteria) this;
		}

		public Criteria andRegist_timestampIn(List<Date> values) {
			addCriterion("regist_timestamp in", values, "regist_timestamp");
			return (Criteria) this;
		}

		public Criteria andRegist_timestampNotIn(List<Date> values) {
			addCriterion("regist_timestamp not in", values, "regist_timestamp");
			return (Criteria) this;
		}

		public Criteria andRegist_timestampBetween(Date value1, Date value2) {
			addCriterion("regist_timestamp between", value1, value2, "regist_timestamp");
			return (Criteria) this;
		}

		public Criteria andRegist_timestampNotBetween(Date value1, Date value2) {
			addCriterion("regist_timestamp not between", value1, value2, "regist_timestamp");
			return (Criteria) this;
		}

		public Criteria andUpdate_timestampIsNull() {
			addCriterion("update_timestamp is null");
			return (Criteria) this;
		}

		public Criteria andUpdate_timestampIsNotNull() {
			addCriterion("update_timestamp is not null");
			return (Criteria) this;
		}

		public Criteria andUpdate_timestampEqualTo(Date value) {
			addCriterion("update_timestamp =", value, "update_timestamp");
			return (Criteria) this;
		}

		public Criteria andUpdate_timestampNotEqualTo(Date value) {
			addCriterion("update_timestamp <>", value, "update_timestamp");
			return (Criteria) this;
		}

		public Criteria andUpdate_timestampGreaterThan(Date value) {
			addCriterion("update_timestamp >", value, "update_timestamp");
			return (Criteria) this;
		}

		public Criteria andUpdate_timestampGreaterThanOrEqualTo(Date value) {
			addCriterion("update_timestamp >=", value, "update_timestamp");
			return (Criteria) this;
		}

		public Criteria andUpdate_timestampLessThan(Date value) {
			addCriterion("update_timestamp <", value, "update_timestamp");
			return (Criteria) this;
		}

		public Criteria andUpdate_timestampLessThanOrEqualTo(Date value) {
			addCriterion("update_timestamp <=", value, "update_timestamp");
			return (Criteria) this;
		}

		public Criteria andUpdate_timestampIn(List<Date> values) {
			addCriterion("update_timestamp in", values, "update_timestamp");
			return (Criteria) this;
		}

		public Criteria andUpdate_timestampNotIn(List<Date> values) {
			addCriterion("update_timestamp not in", values, "update_timestamp");
			return (Criteria) this;
		}

		public Criteria andUpdate_timestampBetween(Date value1, Date value2) {
			addCriterion("update_timestamp between", value1, value2, "update_timestamp");
			return (Criteria) this;
		}

		public Criteria andUpdate_timestampNotBetween(Date value1, Date value2) {
			addCriterion("update_timestamp not between", value1, value2, "update_timestamp");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table hamakko.t_chusen_info
	 * @mbg.generated  Tue Jun 16 11:46:38 JST 2020
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table hamakko.t_chusen_info
     *
     * @mbg.generated do_not_delete_during_merge Tue Jun 16 11:38:38 JST 2020
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }
}