package com.nami.hamakko.mybatis.domain;

import java.util.Date;

public class TChusenInfoKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hamakko.t_chusen_info.sisetsu_code
	 * @mbg.generated  Tue Jun 16 11:46:38 JST 2020
	 */
	private String sisetsu_code;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hamakko.t_chusen_info.yoyaku_jikan
	 * @mbg.generated  Tue Jun 16 11:46:38 JST 2020
	 */
	private Date yoyaku_jikan;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hamakko.t_chusen_info.sisetsu_code
	 * @return  the value of hamakko.t_chusen_info.sisetsu_code
	 * @mbg.generated  Tue Jun 16 11:46:38 JST 2020
	 */
	public String getSisetsu_code() {
		return sisetsu_code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hamakko.t_chusen_info.sisetsu_code
	 * @param sisetsu_code  the value for hamakko.t_chusen_info.sisetsu_code
	 * @mbg.generated  Tue Jun 16 11:46:38 JST 2020
	 */
	public void setSisetsu_code(String sisetsu_code) {
		this.sisetsu_code = sisetsu_code == null ? null : sisetsu_code.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hamakko.t_chusen_info.yoyaku_jikan
	 * @return  the value of hamakko.t_chusen_info.yoyaku_jikan
	 * @mbg.generated  Tue Jun 16 11:46:38 JST 2020
	 */
	public Date getYoyaku_jikan() {
		return yoyaku_jikan;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hamakko.t_chusen_info.yoyaku_jikan
	 * @param yoyaku_jikan  the value for hamakko.t_chusen_info.yoyaku_jikan
	 * @mbg.generated  Tue Jun 16 11:46:38 JST 2020
	 */
	public void setYoyaku_jikan(Date yoyaku_jikan) {
		this.yoyaku_jikan = yoyaku_jikan;
	}
}